rules:
  - id: hardcoded-password
    pattern: password = "..."
    message: "Hardcoded password found — avoid storing secrets in code!"
    severity: ERROR
    languages: [python]
    metadata:
      category: security
